package com.wiziq.service.course.model;

import java.util.Date;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.domain.Persistable;


public class AuditorModel implements Persistable<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5848030456495168879L;

	@Id
	private String id;
	
	@Version  
    private Long version;

	private Date createdDate;
	private Date lastModifiedDate;
	

	@Override
	public boolean isNew() {
		/**
		 * Assuming the Id is generated by database. If not, then need to
		 * override in each model depending on how to identify if a Model is a
		 * new one or already saved Model.
		 **/
		return id == null;
	}
	
	@Override
	public String getId() {
		return id;
	}

	public String setId(String id) {
		return this.id = id;
	}

	public Long getVersion(){
		return version;
	}
	
	public void setVersion(Long version){
		this.version = version;
	}
	
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date creationDate) {
		this.createdDate = creationDate;
	}
	

	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;

	}

	public String getCreatedBy() {
		// TODO Add created by -- Auditor
		return null;
	}

	public void setCreatedBy(String createdBy) {
		// TODO Add created by -- Auditor

	}

	public String getLastModifiedBy() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		// TODO Auto-generated method stub

	}

}
