info:
  tfourth: 1
---
spring:
  profiles: dev
info:
  application: application dev
  component: ${eureka.instance.metadataMap.instanceId}
  tsecond: 2
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadataMap:
      hostname: ${vcap.application.application_uris[0]}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
---
spring:
  profiles: test
info:
  application: application dev
  component: ${eureka.instance.metadataMap.instanceId}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadataMap:
      hostname: ${vcap.application.application_uris[0]}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}


#logging:
#  file: /var/log/wiziq/infrastucture/${spring.application.name}
